remote_theme: pages-themes/cayman # Cayman 테마의 특정 버전 (최신 버전은 GitHub에서 확인)
plugins:
  - jekyll-remote-theme

title: Junyoung Yang  # 사이트 제목 (필수)
description: Scientific Portfolio and Research Insights  # 간단한 설명 (필수)
show_downloads: false  # 다운로드 버튼 표시 여부 (선택)
google_analytics:
