remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

title: Junyoung Yang  # 사이트 제목 (필수)
description: Scientific Portpolio personal website  # 간단한 설명 (필수)
show_downloads: false  # 다운로드 버튼 표시 여부 (선택)
theme: jekyll-theme-cayman
